#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---
apiVersion: v1
kind: Secret
metadata:
  name:  cert-injection-webhook-tls
  namespace: #@ data.values.namespace
---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  ca-cert-data
  namespace: #@ data.values.namespace
data:
  ca.crt: #@ base64.encode(data.values.ca_cert_data)
---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  setup-ca-certs-image
  namespace: #@ data.values.namespace
data:
  image: #@ data.values.setup_ca_certs_image
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-injection-webhook
  namespace: #@ data.values.namespace
  labels:
    app: cert-injection-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-injection-webhook
  template:
    metadata:
      labels:
        app: cert-injection-webhook
    spec:
      serviceAccountName: cert-injection-webhook-sa
      #@ if data.values.image_pull_secrets:
      imagePullSecrets:
        #@ for secret in data.values.image_pull_secrets:
        - name: #@ secret
        #@ end
      #@ end
      containers:
        - name: server
          image: #@ data.values.pod_webhook_image
          imagePullPolicy: Always
          args:
            - --
            - pod-webhook
            #@ for label in data.values.labels:
            - #@ "-label={}".format(label)
            #@ end
            #@ for annotation in data.values.annotations:
            - #@ "-annotation={}".format(annotation)
            #@ end
          volumeMounts:
            - name: webhook-ca-cert
              mountPath: /run/config_maps/ca_cert
              readOnly: true
          ports:
            - containerPort: 8443
              name: cert-injection-webhook-port
          env:
            - name: HTTP_PROXY
              value: #@ data.values.http_proxy
            - name: HTTPS_PROXY
              value: #@ data.values.https_proxy
            - name: NO_PROXY
              value: #@ data.values.no_proxy
            - name: SETUP_CA_CERTS_IMAGE
              valueFrom:
                configMapKeyRef:
                  name: setup-ca-certs-image
                  key: image
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: webhook-ca-cert
          configMap:
            name: ca-cert-data
---
apiVersion: v1
kind: Service
metadata:
  name: cert-injection-webhook
  namespace: #@ data.values.namespace
spec:
  selector:
    app: cert-injection-webhook
  ports:
    - port: 443
      targetPort: cert-injection-webhook-port
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: defaults.webhook.cert-injection.tanzu.vmware.com
webhooks:
  - name: defaults.webhook.cert-injection.tanzu.vmware.com
    clientConfig:
      service:
        name: cert-injection-webhook
        namespace: #@ data.values.namespace
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-injection-webhook-sa
  namespace: #@ data.values.namespace